parsecmgmt2 now supports old bldconf, e.g., {gcc,icc}-{pthreads,tbb,openmp,serial}

diff --git a/bin/parsecmgmt2 b/bin/parsecmgmt2
--- a/bin/parsecmgmt2
+++ b/bin/parsecmgmt2
@@ -805,6 +805,18 @@ Examples (3) [NEW: SPLASH-2 Suite and SPLASH-2x Suite]:
 
   export PARSECPLAT
   # Load build configuration
+  if [[ $build != *"task"* ]]; then
+    if [[ $action == *"build"* ]]; then
+      buildfile="${PARSECDIR}/config/${build}.bldconf"
+      if [ -f "${buildfile}" ]; then
+        echo "${oprefix} Source global build configuration file '${buildfile}'."
+        source ${buildfile}
+      else
+        echo "${oprefix} Error: Cannot find build configuration file '${buildfile}'."
+        exit 1
+      fi
+    fi
+  fi
 #  if [ "${action}" == "build" -o "${action}" == "run" ]; then
 #    source_global_bldconf ${build}
 #  fi
@@ -990,8 +1002,18 @@ function build_package {
   fi
 
   # Source local build configuration to get dependencies
-  source_global_bldconf ${pkg} ${build}
-  source_local_bldconf ${build}
+  if [[ $build == *"task"* ]]; then
+    source_global_bldconf ${pkg} ${build}
+    source_local_bldconf ${build}
+  else
+    if [ ! -f "${pkgparsecdir}/${build}.bldconf" ]; then
+      echo "${oprefix} Error: Cannot find local build configuration '${build}.bldconf' for package ${pkg}." 2>&1 | ${TEE} ${log}
+      exit 1
+    else
+      echo "${oprefix} Source local build configuration file '${pkgparsecdir}/${build}.bldconf'."
+      source ${pkgparsecdir}/${build}.bldconf
+    fi
+  fi
 
   # Build packages on which pkg depends
   if [ -z "${global_build_deps}" -a -z "${build_deps}" ]; then
@@ -1016,8 +1038,17 @@ function build_package {
   echo "${oprefix} [---------- Building package ${pkg} ----------]" 2>&1 | ${TEE} ${log}
 
   # Source local package build configuration again (might have gotten overwritten by recursion)
-  source_global_bldconf ${pkg} ${build}
-  source_local_bldconf ${build}
+  if [[ $build == *"task"* ]]; then
+    source_global_bldconf ${pkg} ${build}
+    source_local_bldconf ${build}
+  else
+    if [ ! -f "${pkgparsecdir}/${build}.bldconf" ]; then
+      echo "${oprefix} Error: Cannot find local build configuration '${build}.bldconf' for package ${pkg}." 2>&1 | ${TEE} ${log}
+      exit 1
+    else
+      source ${pkgparsecdir}/${build}.bldconf
+    fi
+  fi
 
   # Check for obvious errors
   if [ -z "${build_inplace}" ]; then
